version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
        pkg-manager: npm
      - restore_cache:
        keys: node-deps-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
        name: Install Dependencies
        command: npm ci
      - save_cache:
        key: node-deps-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
        paths:
          - node_modules
      - run:
        name: Run tests
        command: npm run test

workflows:
  main-workflow:
    jobs:
      - build-and-test
      # - node/test
